import type { Metadata } from "next";
import "./globals.css";

import { Poppins,  Alegreya, Dancing_Script } from "next/font/google";
import { StudioNavbar } from "@/components/navbar-home";


//###### Las fuentes tienen que definirse en el layout, el el css y tailwind.config.ts####### ///
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
})

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  weight: [ "400", "500", "600", "700"], 
  variable: "--font-dancingScript",
});

const alegreya = Alegreya({
  subsets: ["latin"],
  weight: [ "400", "500", "600", "700", "800", "900"],
  variable: "--font-alegreya",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
    
    <html lang="en">
     
      <body 
        className={`${poppins.variable} ${alegreya.variable} ${dancingScript.variable}`} 
        
        >
      <main className="min-h-screen">
      <StudioNavbar />
        {children}
      </main>
      </body>
       
    </html>
  );
}
