import type { Metadata } from "next";
import "./globals.css";
import { StudioNavbar } from "./modules/home/components/navbar-home";
import { Poppins, Libre_Baskerville } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
})

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-libre-baskerville",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <body 
        className={`${poppins.variable} ${libreBaskerville.className}`} 
        
        >
      <StudioNavbar />
      <main className="min-h-screen">
        {children}
      </main>
      </body>
       
    </html>
  );
}
